### ISSUE TITLE
add a mcollective wait task

### ISSUE THREAD

**Issue by ripienaar** [ripienaar/mcollective-choria#109]
Until MCollective have macros we need some stop gap, I think a good option is to make a mco request and check the value of some resulting data matches a expression.

This is a gigantic hack but will do the trick:

```yaml
tasks:
  - mcollective:
      description: Disable all nodes
      action: puppet.disable
      nodes: "{{{ nodes.dev }}}"

  - mcollective_wait:
      description: Wait for Puppet to go idle
      action: puppet.status
      nodes: "{{{ nodes.dev }}}"
      pre_sleep: 0
      tries: 10
      try_sleep: 30
      expression:
        - :idling
        - ==
        - true
```

This solves the problem where you want to have puppet disabled on a set of nodes before doing maintenance, so you have to wait for the Puppet runs all to stop as well before your maintenance can go on, this lets you do that.
