### ISSUE TITLE
Should support data sources

### ISSUE THREAD

**Issue by ripienaar** [ripienaar/mcollective-choria#149]
A data source is some kind of k/v store like consul, etcd or just memory.

There should be named sets of these with different implementations of data store.

```yaml
data_stores:
  consul_store:
    type: consul
    session_ttl: 300
    dc: foo
```

They should be used to resolve inputs when not specifically given on the cli:

```yaml
inputs:
  cluster:
    description: "Cluster to deploy"
    type: "String"
    required: true
    data: "consul_store/web_app_cluster_name"
```

When an input is not given it should consult the data store, this should be done on every attempt to read the input to facilitate the value changing during playbook runtime

Tasks should be able to write and delete them:

```yaml
tasks:
  - data:
      action: "write"
      key: "dc_store/web_app_cluster_name"
      value: "alpha"

  - shell:
      command: "update_app.sh --cluster {{{ inputs.cluster }}}"

  - data:
      action: "delete"
      key: "dc_store/web_app_cluster_name"
      recurse: true                        
```

Here the command will be run with `---cluster alpha`

A memory store should be included at first
