### ISSUE TITLE
create a playbook like system

### ISSUE THREAD

**Issue by ripienaar** [ripienaar/mcollective-choria#32]
Full spec for the feature @ http://choria.io/docs/roadmap/playbooks/

**Comment by igalic** [comment]
what are shell::resource / shell::system in this dsl?

**Comment by ripienaar** [comment]
something I am/was playing with to see how a shell script like thing might look.  It's interesting but annoying.

What I really want is to be able to just use resources as is but top down and with functions in between, this cant be done with puppet as is so I was hacking around with these functions.

**Comment by ripienaar** [comment]
Been tinkering with this idea on and off for ages, here's another stab I took not long ago:

Key to this is helpers provided by agent plugins, for example `puppet.wait_till_idle` is a piece of client side code that the agent plugin can provide and it implements a thing that polls the supplied nodes every `n` seconds until they are all idle.

The above linked Ruby example have such helpers - though they're nothing at all like whats needed.  Point being today the agents just give DDL hints, I want them to give snippets of utility function that can be reused.

Here is a playbook that does a bunch of things new and interesting:

  * Version validates agent versions locally and on the network are within expected
  * Can be run from CLI or a REST service, they aren't interactive but can be bootstrapped from the CLI and run on demand for sure
  * Potentially integrates with Puppet Application Orchestrator thing as discovery source which is rather interesting
  * Have various types of tasks like `rpc`, `webhook`, above `helpers`, `slack` call out etc
  * Various post hooks for feeding into other services
  * These same helpers and basic abilities can be usable from ruby scripts too as a new kind of `application` plugin thats less shitty.

```yaml
# A playbook spec for mcollective and the choria security system
#
# Intention is these will run in a service generally, you'd post them
# to the service via a REST gateway and request they are run on some
# schedule or on demand
#
# These can also be run from the CLI and they will take cli inputs like
# --backend and --revision here, if not given and on the CLI it can ask
# for these inputs.
#
# Since the inputs are in the form of data web UIs can exist automatically
# too as per agents with DDLs.
#
# Running a playbook via REST will give a job id users can later query.
#
# Actually running these in the service context might mean using a per job
# instance docker container to make them resistant to restarting / failure
# of the REST service.

name: web app deploy
version: 1.2.3
author: R.I.Pienaar <rip@devco.net>
description: A play book to deploy a foo

# sets the caller id to this when running under
# the service, when ran interactively current
# user credentials are used, choria security
# systems allows privileged certs to set
# arbitrary callers...so action policy, audit
# logs etc all would see this
run_as: deployer

# validates DDLs on the client node and when discovery
# on nodes set `needs` it will validate those same
# specifications are on the servers in question via
# rpcutil#agent_inventory
uses:
  - agent: rpcutil
    version: semverspec
  - agent: haproxy
    version: semverspec
  - agent: appmgr
    version: semverspec
  - agent: nrpe
    version: semverspec
  - agent: puppet
    version: semverspec

# this would need to be very similar to the options in
# application plugins since these when run on the CLI
# will become exactly that
inputs:
  backend:
    description: HAProxy Backend
    required: true
    type: String
    validation: /[a-zA-Z0-9]+/   # also mco validators

  revision:
    description: Git revision to deploy
    required: true
    type: String

  cluster:
    description: The cluster name based on cluster fact
    required: false
    default: alpha
    type: String

  canaries:
    description: Limit the chosen webservers to this ammount
    required: false
    default: ~
    type: String

  batch:
    description: Deploy to webservers in batches of this many
    required: false
    default: 2
    type: Integer

# pre discovered static lists of nodes validated for connectivity
# and meeting spec of the agents as per above uses section, though
# tasks can just hard code node lists too if they so wish
nodes:
  load_balancers:
    type: mcollective
    discovery_method: choria
    agent: haproxy
    at_least: 1
    when_empty: "No load balancers found with class haproxy"
    test: true # rpcutil#ping them to catch puppetdb vs reality issues
    needs: [haproxy, rpcutil]

  web_servers:
    type: mcollective
    discovery_method: choria
    agent: appmgr
    fact: cluster=${input.cluster}
    at_least: 1
    limit: ${input.canaries} # picks a canary, if canaries is nil this is noop and all is chosen
    when_empty: "No web servers found in cluster ${input.cluster}"
    test: true # rpcutil#ping them to catch puppetdb vs reality issues
    needs: [appmgr, rpcutil, nrpe]

# an interesting alternative is to query a puppet 4 app stack
# this way we could potentially orchestrate one off actions against
# the definitions found in a puppet app stack - effectively using
# those as a discovery source, here the 'puppet_site' is a special
# kind of discovery plugin thing so you can make it query anything
#
# and of course any kind of mixing and matching is possible, its just
# discovery plugins that returns arrays of host identities
#
# nodes:
#   load_balancers:
#     type: puppet_site
#     environment: production
#     application: Lamp[app1]
#     resource_type: Lamp::Haproxy
#
#   web_servers:
#     type: puppet_site
#     environment: production
#     application: Lamp[app1]
#     resource_type: Lamp::Webapp
#
# this might be handy on the CLI somehow too

tasks:
  # announce - logs
  # helper - calls a specific helper class shipped with the agent plugin
  # rpc - std mco rpc call
  # webhook - hits up a webhook
  # slack - sends to a slack channel
  # playbook - another playbook
  # etc..plugins to the orchestrator things like consul, etcd etc super useful

  - rpc:
      nodes: ${nodes.web_servers}
      action: puppet.disable
      properties:
        message: Disabled during playbook execution of ${state.playbook.name}

  # uses a helper to repeatedly checks puppet status waiting until they are all idle
  # this is a helper plugin the puppet agent will deliver to clients and usable here
  # or in application plugins this basic logic: http://srt.ly/waittillidle
  - helper:
      nodes: ${nodes.web_servers}
      name: puppet.wait_till_idle
      arguments:
        checks: 30
        sleep: 10
        
  - rpc:
      nodes: ${nodes.load_balancers}
      action: haproxy.disable
      properties:
        servers: ${nodes.web_servers}
        backend: ${input.backend}

  - rpc:
      nodes: ${nodes.web_servers}
      action: appmgr.upgrade
      properties:
        revision: ${input.revision}
      batch_size: ${input.batch}
      tries: 2

  - rpc:
      nodes: ${nodes.web_servers}
      action: nrpe.runcommand
      properties:
        command: check_load
      tries: 10
      try_sleep: 30
      on_fail: Not all servers recovered after deployment, servers will remain disabled on LB

  - rpc:
      nodes: ${nodes.load_balancers}
      action: haproxy.enable
      properties:
        servers: ${nodes.web_servers}
        backend: ${input.backend}

  - rpc:
      nodes: ${nodes.web_servers}
      action: appmgr.status
      post:
        - summarize

  - rpc:
      nodes: ${nodes.web_servers}
      action: puppet.enable

  - announce: Cluster ${input.cluster} updated to revision ${input.revision}

hooks:
  # pre_task - before every task
  # post_task - after every task
  # on_fail - if anything fails
  # on_success - if the book finishes all tasks
  # pre_book - before the book
  # post_book - after the book
  on_fail:
    - webhook: https://.....
    - slack:
        room: ops
        message: foo

    - playbook:
        name: deploy_failure_handler
        inputs:
          revision: ${input.revision}
          cluster: ${input.cluster}
          backend: ${input.backend}

  on_success:
    - webhook: https://.....
    - slack:
        room: ops
        message: foo
```
