### ISSUE TITLE
Add a REST task type

### ISSUE THREAD

**Issue by ripienaar** [ripienaar/mcollective-choria#96]
Make a generic REST client task type, get/put/post etc, just send JSON

**Comment by ripienaar** [comment]
A POST will just JSON encode the data and POST it as `application/json`:

```yaml
- rest
    uri: http://some/url
    method: POST
    data:
       foo: bar
```

A GET will turn each data item into a url encoded argument

```yaml
- rest
    uri: http://some/url
    method: GET
    data:
       foo: bar
```

A useful user agent should be set
